### ISSUE TITLE
"Unexpected character encountered when parsing value" error on .NET 6 / Angular 14 app startup

### ISSUE THREAD

**Issue by jitterbox** [MintPlayer/MintPlayer.AspNetCore.SpaServices.Routing#21]
After following [your instructions](https://github.com/dotnet/AspNetCore.Docs/issues/12434#issuecomment-1277158232), and [this suggestion](https://github.com/angular/universal/issues/1848#issuecomment-867212235) to fix ECONNREFUSED issue, I'm now encountering this error in the .NET app, caught by general exception handler:
`Unexpected character encountered while parsing value: {. Path 'errorMessage', line 1, position 17.`
Call stack: 
```
at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType) in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 726
   at Newtonsoft.Json.JsonTextReader.ReadAsString() in /_/Src/Newtonsoft.Json/JsonTextReader.cs:line 490
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter) in /_/Src/Newtonsoft.Json/JsonReader.cs:line 1221
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2411
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 502
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 309
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 173
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 904
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 883
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 831
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in /_/Src/Newtonsoft.Json/JsonConvert.cs:line 787
   at MintPlayer.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
   at MintPlayer.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.<InvokeExportAsync>d__13`1.MoveNext()
   at MintPlayer.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()
   at MintPlayer.AspNetCore.SpaServices.Prerendering.SpaPrerenderingExtensions.<>c__DisplayClass0_0.<<UseSpaPrerendering>b__1>d.MoveNext()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext() in /_/src/Http/Routing/src/RouterMiddleware.cs:line 52
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext() in /_/src/Security/Authentication/Core/src/AuthenticationMiddleware.cs:line 83
   at XXXXXX.Middleware.ArmNewsPostMiddleware.<Invoke>d__2.MoveNext() in D:\X\NewsPostMiddleware.cs:line 56
   at XXXXXX.Middleware.ArmSitemapMiddleware.<Invoke>d__2.MoveNext() in D:\X\Middleware\SitemapMiddleware.cs:line 43
   at XXXXXX.Middleware.ArmExceptionHandler.<InvokeAsync>d__4.MoveNext() in D:\X\Middleware\ExceptionHandler.cs:line 37
```
I _assume_ this has to do with either an Angular/Node.js configuration issue or something incorrect about data coming from the Angular app(?).

In the VS output window, this is the stack trace that appears at the same time:
```
Microsoft.AspNetCore.NodeServices: Error: ERROR NetworkError
    at XMLHttpRequest3.send (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:1147966)
    at Observable._subscribe (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:6163696)
    at Observable._trySubscribe (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:960030)
    at Observable.subscribe (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:959812)
    at DoOperator.call (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:1047007)
    at Observable.subscribe (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:959666)
    at scheduleTask (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:8602617)
    at Observable._subscribe (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:8603220)
    at Observable._trySubscribe (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:960030)
    at Observable.subscribe (D:\Source\Repos\ARMAMS\ARMAMS\ClientApp\dist\ClientApp\server\main.js:1:959812)
```
When I look at the error site in `main.js`, it's this error from the XHR Send() method:
`throw new NetworkError('Unsupported protocol ${this._url.protocol}')`
...I would expect the cause to be SSR trying to process a relative URL instead of an absolute one, but I can't discover how to trace that back any further into where in the Angular app this might be happening.

Any thoughts on whether this could be the cause, or have you seen anything similar?
Is there anything in `NodeServices` (or elsewhere) to help debug or reveal the original site of the error thrown in the Angular app?

I had originally attempted to add a [custom HTTP Interceptor](https://bcodes.io/blog/post/angular-universal-relative-to-absolute-http-interceptor) to ensure all URLs were converted, but it didn't seem to work.

**Comment by jitterbox** [comment]
@PieterjanDeClippel let me know if there's any chance of getting some help working on this - I can be reached at the e-mail on my profile. Thanks!
